on:
  push:
    branches:
    - main
  pull_request:
name: integration
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.8.1
    # Build with JDK 11 and run tests with JDK 8
    - uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: zulu
    - run: echo "JAVA11_HOME=${JAVA_HOME}" >> $GITHUB_ENV
      shell: bash
    # GraalVM dependencies require JDK 11 to compile the classes touching GraalVM classes.
    - name: Install project
      run: mvn clean install
      working-directory: google-cloud-spanner
    - uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: zulu
    - run: echo "JAVA8_HOME=${JAVA_HOME}" >> $GITHUB_ENV
      shell: bash
    - run: java -version
    - name: Run unit tests
      run: mvn test -B -V -Dclirr.skip=true -Denforcer.skip=true -Djava.net.preferIPv4Stack=true
      working-directory: google-cloud-spanner
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      working-directory: google-cloud-spanner
      with:
        directory: ./target/site/jacoco-unit-test-coverage-report
        fail_ci_if_error: true
        flags: all_tests
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true