on:
  push:
    branches:
    - main
  pull_request:
name: integration
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v3
    - uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.8.1
    # Build with JDK 11 and run tests with JDK 8
    - uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: zulu
    - run: echo "JAVA11_HOME=${JAVA_HOME}" >> $GITHUB_ENV
      shell: bash
    - uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: zulu
    - run: echo "JAVA8_HOME=${JAVA_HOME}" >> $GITHUB_ENV
      shell: bash
    - run: java -version
    - name: Compiling main library
      run: .kokoro/build.sh
    - name: Run unit tests
      run: mvn test -B -Ptest-all
    - name: Run integration tests
      run: mvn verify -B -ntp -Penable-integration-tests -Djava.net.preferIPv4Stack=true -DtrimStackTrace=false -Dclirr.skip=true -Denforcer.skip=true -Dmaven.main.skip=true
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./target/site/jacoco-merged-test-coverage-report
        fail_ci_if_error: true
        flags: all_tests
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true